### ISSUE TITLE
Can't define the workdir of the action

### ISSUE THREAD

**Issue by kevinblanco** [ShiftLeftSecurity/scan-action#12]
Hello, 

I'm trying to use your action to scan a Node.js project using the Github Action. The github `yml` definition lives in the`.github/workspace` and when the Shiftleft scan is executed, its scanning that folder, which has nothing in it. I need the action to be ran in the root of the repository, where the actual code lives. 

As you can see here, is scanning that folder: 

```
[17:09:12] INFO     Scanning /github/workspace using plugins ['nodejs', 'credscan', 'depscan']                                              
                                     SAST Scan Summary                                     
```
And I see that in the job run: 
```
Run ShiftLeftSecurity/scan-action@master
/usr/bin/docker run --name shiftleftsastscanlatest_c4b073 --label 87c201 --workdir /github/workspace
```

I tried defining the working directory for the Action: 

```
defaults:
  run:
    working-directory: ./server
```

But that did not worked either. 

Can you please explain how to define the `--workdir` shiftleft scan uses for the Action Job? 

Thanks

**Comment by prabhu** [comment]
Hi @kevinblanco 

The work dir parameter is set by github action and I'm not sure if it is possible to customize that. To specify an input directory for scan use `src` argument.

```yaml
- name: Perform ShiftLeft Scan
  uses: ShiftLeftSecurity/scan-action@master
  with:
    type: "credscan,java,depscan"
    src: /github/workspace/<directory>
```

Also scan should automatically ignore .github directory while scanning so not sure what is going on - https://github.com/ShiftLeftSecurity/sast-scan/blob/master/lib/config.py#L113

**Comment by kevinblanco** [comment]
Thanks, the `src` argument seems to do the job! Not sure if that is documented somewhere. 

Thanks
