### ISSUE TITLE
Changed Files Analysis

### ISSUE THREAD

**Issue by pietrodellamore** [ShiftLeftSecurity/scan-action#16]
We are currently running shift left scan for our Terraform files.

In order to create a optimized workflow and generating a good backlog for our team, we would want to analyze just the changed files on that Pull Request.

Is there a way to configure this type of behaviour for shift left scan?

**Comment by prabhu** [comment]
Hi @pietrodellamore 

This feature is not possible to implement because of the way scan is designed. Also, from experience I can say that a change made in one code or configuration would actually impact some other code or module so it is always best to scan the full repo. Out of curiosity, what sort of timing are you seeing so that we can figure out a way to optimize the workflow without the need for incremental scanning.

**Comment by prabhu** [comment]
Also, note that this repo belongs to scan the opensource product. If you are using the Next Gen analysis product, please raise a request via the support option in the dashboard.

**Comment by pietrodellamore** [comment]
> Hi @pietrodellamore
> 
> This feature is not possible to implement because of the way scan is designed. Also, from experience I can say that a change made in one code or configuration would actually impact some other code or module so it is always best to scan the full repo. Out of curiosity, what sort of timing are you seeing so that we can figure out a way to optimize the workflow without the need for incremental scanning.

So sad to hear that.

The optimizing are not on timing, but on security findings segregation. For example: If we already have 200 issues on master (legacy code), and 1 developer creates a new PR, it is easier for the developer to see the analysis of that Pull Request files and faster for fixing the issues of that PR (this way we ensure that quality never goes down). 

But with full scan, when he sees like 200 issues, it is more likely that he will not want to spend his time on fixing this issues (sometimes, he can't even find his security issue on the scan result because there are a lot of legacy issues). 

There isn't a way to pass an environment variable with the file to be analyzed? This way we can create a list of files modified and then scan 1 by 1 on a for loop (for example).

**Comment by prabhu** [comment]
The feature you are asking is available with our commercial product called ShiftLeft NextGen which is also free for up to 5 members. There are good compare api available that allows the viewing only new, common, fixed vulnerabilities etc. Please [register](https://www.shiftleft.io/register) and take a look at the [compare api](https://docs.shiftleft.io/api/#operation/Comparetwoscans) 

On the opensource product, see if GitHub Code scanning has a way of filtering based on PR. I will think about a way of defining baselines meanwhile.

**Comment by pietrodellamore** [comment]
> The feature you are asking is available with our commercial product called ShiftLeft NextGen which is also free for up to 5 members. There are good compare api available that allows the viewing only new, common, fixed vulnerabilities etc. Please [register](https://www.shiftleft.io/register) and take a look at the [compare api](https://docs.shiftleft.io/api/#operation/Comparetwoscans)
> 
> On the opensource product, see if GitHub Code scanning has a way of filtering based on PR. I will think about a way of defining baselines meanwhile.

Interesting. I'm going to take a look at it.

Users are counted by Pull Request/Commit authors or only whose that have dashboard access?

Thanks!

**Comment by prabhu** [comment]
Based on dashboard access.
