### ISSUE TITLE
Action got stuck at no-case (72%)

### ISSUE THREAD

**Issue by pihart** [ShiftLeftSecurity/scan-action#27]
https://github.com/cjquines/qboard/runs/2103832681?check_suite_focus=true

[logs_131.zip](https://github.com/ShiftLeftSecurity/scan-action/files/6135684/logs_131.zip)

Interrupted it and reran, where it [completed successfully](https://github.com/cjquines/qboard/runs/2103935367?check_suite_focus=true).

(This may be an issue with the underlying docker container or its dependent code. Let me know if I should move this issue elsewhere.)

**Comment by prabhu** [comment]
Hi @pihart 

That particular issue is with a recently launched oss risk audit feature. The feature queries npm for every package to compute the risk score. I think what has happened is that for that particular package no response was sent by npm and the connection didn't timeout.

I will take this as a defect and timeout to npm. Meanwhile to disable risk audit you can set the environment variable `ENABLE_OSS_RISK` to `""` blank value.

https://slscan.io/en/latest/getting-started/#environment-variables

**Comment by prabhu** [comment]
I have resolved this issue and added timeout along with a circuit breaker for oss risk audit. No changes are required in your pipeline and scan should be able to handle slow responses from npm better now. Thanks for reporting the issue!

**Comment by pihart** [comment]
Thank you for the prompt resolution!

Do you think there may be some deeper issue, though? It seems to have attempted to audit no-case over 1600 times.

Maybe you make an initial network request and treat its data as fact. You then use the output of that call to make more network requests against npm, with the assumption that it won't change. If this is the case, a possible solution would be re-running the initial request after a number of failed audits.

(I also don't see no-case, along with some other packages, in the logs of the successful run. Is this expected?)

**Comment by prabhu** [comment]
@pihart that was due to the progress bar. When depscan is run locally the progress bar would stay in place and show the nice scrolling effect. On a CI environment, each such refresh is being logged into a new line on the UI.

This is place in the code where I added the timeout - https://github.com/AppThreat/dep-scan/blob/master/depscan/lib/pkg_query.py#L73 . Please feel free to take a look and let me know in case you spot something.

**Comment by pihart** [comment]
That makes sense, thank you.

It doesn't look like you're making queries based on the result of another query; the lookup URL is computed directly from the package. I have opened https://github.com/AppThreat/dep-scan/pull/35 to provide the option to at least retry requests that error due to timeout.
